services:
  backend:
    image: tcc-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/fiscaliza_db
      - API_KEY=${API_KEY} # obtido  .env na pasta raiz do projeto
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - tcc-network
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "python scripts/init_db.py && python scripts/scraper.py && python main.py"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  frontend:
    image: tcc-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - tcc-network
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      backend:
        condition: service_healthy

  postgres:
    image: postgres:18
    container_name: database
    environment:
      POSTGRES_DB: fiscaliza_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - tcc-pgdata:/var/lib/postgresql/data
    networks:
      - tcc-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fiscaliza_db"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 0s

networks:
  tcc-network:
    name: tcc-network
    driver: bridge

volumes:
  tcc-pgdata:
    name: tcc-pgdata
